### ISSUE TITLE
paper-menu-button doesn't open in Chrome device mode

### ISSUE THREAD

**Issue by JustinXinLiu** [PolymerElements/paper-menu-button#11]
Please open this page (https://elements.polymer-project.org/elements/paper-menu-button?active=paper-menu-button&view=demo:demo/index.html) in Chrome. Hit F12 and enable device mode, then select Apple iPad and refresh the page.

Now, if you only tap on the right part (close to the edge) of the blue `Dinosaurs` button, you will see the ripple effect appear but the drop down doesn't open.

Please note that I've already got the latest version of iron-dropdown (currently 1.0.3) and this issue only appears to happen when you have device mode enabled.

**Comment by firasdib** [comment]
I have this issue too. If I don't press the element dead on, the popup does not open. This was clearer when I tried it on a `paper-fab`.

**Comment by cdata** [comment]
Closing this, as the problem appears to be fixed. Please re-open if there is still a problem!
