### ISSUE TITLE
2.0-preview readme needs to reference using slot instead of class to define the trigger

### ISSUE THREAD

**Issue by mbinette** [PolymerElements/paper-menu-button#117]
The documentation states

```
<paper-menu-button>
  <paper-icon-button icon="menu" class="dropdown-trigger"></paper-icon-button>
  ...
</paper-menu-button>
```
The 2.0-preview code no longer uses the `class="dropdown-trigger"`. Instead, it should be changed to `slot="dropdown-trigger"`

**Comment by masonlouchart** [comment]
Done here [99036ed](https://github.com/PolymerElements/paper-menu-button/commit/99036edd407b885e55f9b4550c71679a3c088b4f#diff-04c6e90faac2675aa89e2176d2eec7d8)?

**Comment by mbinette** [comment]
Yes, fixed.
