### ISSUE TITLE
ANIMATION_CUBIC_BEZIER undefined

### ISSUE THREAD

**Issue by jasonsavard** [PolymerElements/paper-menu-button#16]
This occurs if I put a <paper-menu-button> element in the html and I load the polymer after. The error also prevents the paper-menu-button from loading correctly.

But if I dynamically insert the <paper-menu-button> element or use templating etc. after the polymer has loaded then there is no issue and the paper-menu-button loads correctly.

Exact error:
Cannot read property 'ANIMATION_CUBIC_BEZIER' of undefined (Occurs inside the method  openAnimationConfig of the paper-menu-button.html)
It's being called before PaperMenuButton is declared.

Workaround:
Currently the ANIMATION_CUBIC_BEZIER is declared at the end of the paper-menu-button.html
But, if I move that declaration to the beginning it resolves the issue, but I have to declare it global by removing the PaperMenuButton.ANIMATION_CUBIC_BEZIER and just using ANIMATION_CUBIC_BEZIER, since the issue is that PaperMenuButton is undefined at the time.

**Comment by pricecreations** [comment]
I confirm that this is the same case for me.  I have implemented the same workaround locally as well.

**Comment by itsashis4u** [comment]
Having the same issue. Is there a better option?

**Comment by rubenstolk** [comment]
+1

**Comment by viridia** [comment]
I just encountered the same issue - is there a workaround?

**Comment by rubenstolk** [comment]
@viridia https://github.com/PolymerElements/paper-menu-button/pull/42
