### ISSUE TITLE
--paper-menu-button-dropdown doesn't apply to iron-dropdown, but rather the paper-material it contains

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-menu-button#17]
It'd be nice to be able to style the ``iron-dropdown`` via this mixin.  I would assume based on its name and description that it is possible to do this, but it is not.

**Comment by blasten** [comment]
is there a reason why `--paper-menu-button-dropdown` isn't sufficient? As far as I can see `iron-dropdown`  https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L48-L50 doesn't have any special styles. @cdata any thoughts?

**Comment by miztroh** [comment]
@blasten As part of a ``paper-menu-button`` implementation, ``iron-dropdown`` gets CSS rules for ``outline``, ``right``, ``top``, ``z-index``, and ``position``.  Those rules may be coming from ``iron-overlay-behavior``.

**Comment by cdata** [comment]
@blasten @miztroh We should probably add some mixins to `iron-dropdown` directly to handle this use case. Perhaps in here:

**Comment by blasten** [comment]
This issue should be fixed by https://github.com/PolymerElements/paper-menu-button/pull/33 The mixins are `--paper-menu-button-dropdown` & `--paper-menu-button-content`
