### ISSUE TITLE
deprecated core-x dependencies

### ISSUE THREAD

**Issue by M0nter0** [PolymerElements/paper-menu-button#2]
Hi!
In [the entry at the Polymer Blog for PolymerElements](https://blog.polymer-project.org/announcements/2015/05/14/updated-elements/) we can read PolymerElements project stores elements 0.8+ compatible elements.

But paper-menu-button has a dependency on core-X elements, in some case, as core-icon, deprecated since 0.5.

Why is paper-menu-button on PolymerElements organization?
It's because it will be upgraded to 1.0?

Thanks

**Comment by notwaldorf** [comment]
This looks like it's been ported to 1.0, so I think this is just an old issue
