### ISSUE TITLE
After a bower update 18/08, paper-menu-button behaviour changed/broke 

### ISSUE THREAD

**Issue by kfayelun** [PolymerElements/paper-menu-button#20]
Last update before this was about a week or 10 days before that. 

Now the first paper-item in the dropdown has focus/pressed state (i.e. it has a grey background) when opening it, but I'm not setting the "selected" attribute on paper-menu. Also it does not propagate the onclick to the method, but this is only for that first paper-item (which also has focus). They other 4 items in the  dropdown works as before, opening dialogs or toasts. 

So when I click the paper-item in the dropdown first time after a refresh, it just closes the dropdown (but the item is grey). But if I open it again and try press it, its like the paper-item is dead, nothing happens, and you have to press outside the menu to close it. OR you can press any of the other items in the list, which will open their respective dialogs/toasts. If you then open the dropdown jet again and try press that first item, lo and behold(!), it now works perfectly, opening the dialog in its onclick method.

This now happens to both of the paper-menu-buttons I'm using in my header. This is one of them:

```html
<paper-menu-button>

    <paper-icon-button icon="menu" class="dropdown-trigger"></paper-icon-button>

    <paper-menu id="headerMenu" class="dropdown-content">

            <paper-item id="item-create" data-dialog="createDialog"> 
              <paper-button id="button-create" onclick="dialogHandler(event)">Create</paper-button>
            </paper-item>

/* these below here all work, the one above does not*/

            <paper-item id="item-open" data-dialog="openDialog"> 
              <paper-button id="button-open" onclick="dialogHandler(event)">Open</paper-button>
            </paper-item>

            <paper-item id="item-save" data-dialog="saveDialog"> 
              <paper-button id="button-save" onclick="document.querySelector('#saveToast').show()">Save</paper-button>
            </paper-item>

            <paper-item id="item-export" data-dialog="exportDialog"> 
              <paper-button id="button-export" onclick="document.querySelector('#exportToast').show()">Export</paper-button>
            </paper-item>

            <paper-item id="item-publish" data-dialog="publishDialog"> 
              <paper-button id="button-publish" onclick="document.querySelector('#publishToast').show()">Publish</paper-button>
            </paper-item>

    </paper-menu>
</paper-menu-button>
```
If I change back to the old bower components before the update, everything works; dialogs open and no "greyed out" paper-items.

**Comment by notwaldorf** [comment]
Did you also update all the dependencies? Unfortunately this is a super old bug, so we can't really see what went wrong with bower. Please re-open if your issue is still happening in the current release
