### ISSUE TITLE
Can not close once opened

### ISSUE THREAD

**Issue by GradyD** [PolymerElements/paper-menu-button#4]
I am using, https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html and when I click on the icon the menu appears but I can't get the menu to close. This can be seen on the demo page.

**Comment by ulrichSchreiner** [comment]
hi,
i have the same problem. if you click outside the menu this happens. if you open the menu and click an item everything works. but as soon as you click outside the menu this bug appears and you cannot close the menu.

**Comment by WrinklyNinja** [comment]
+1, can replicate this too.

1. Click a menu button.
2. Click outside the menu that gets displayed.

There will be a quick menu closing then reopening animation, and then clicking outside the menu has no effect, and clicking on a menu item selects it but does not close the menu.

**Comment by brycethorup** [comment]
This may be related to the default animation or animation capabilities generally since if you add the `no-animations` attribute to the `<paper-menu-button>` element it works fine. I'll try different animations to see what happens.

**Comment by GradyD** [comment]
It appears that this issue is related to https://github.com/PolymerElements/iron-dropdown/pull/8

I haven't had time to test the code but I spoke with @VandeurenGlenn and he said he fixed this issue with code in his PR.

**Comment by Mygod** [comment]
+1

**Comment by yingqiaogit** [comment]
I have seen the same scenario although I set the noAnimations="true"

However, the error showed in the development tool is as:

Uncaught TypeError: Cannot set property 'left' of undefined

Polymer._updateOverlayPosition @ iron-dropdown.html:328
Polymer._onIronResize @ iron-dropdown.html:259
handler @ polymer.html:379
Polymer.Base._addFeature.fire @ polymer.html:1036
Polymer.IronResizableBehavior.notifyResize @ iron-resizable-behavior.html:87
atEndOfMicrotask @ polymer.html:924

Any idea?

**Comment by jscissr** [comment]
This is (probably) a duplicate of PolymerElements/iron-dropdown#9

**Comment by yingqiaogit** [comment]
I did a "bower update", the problem is gone even without the noanimations

**Comment by GradyD** [comment]
This has been fixed with https://github.com/PolymerElements/iron-dropdown/pull/10! Thanks @cdata
