### ISSUE TITLE
Wrong license in bower.json

### ISSUE THREAD

**Issue by vlna** [PolymerElements/paper-menu-button#41]
## Status
`bower.json` contains information package is MIT licensed, html files contain information about BSD licensing.
## Expected change
`bower.json` should contain link to correct license (http://polymer.github.io/LICENSE.txt like rest of PolymerElements) instead of MIT

Line in bower.json

    "license": "MIT",

should be changed to

    "license": "http://polymer.github.io/LICENSE.txt",

**Comment by bryanbierce** [comment]
Hi, I would like to submit the pull request to fix this issue as my first PR and saw point #3 on the CONTRIBUTING.md. Would even this fix require a test?
