### ISSUE TITLE
Problem in close Animation

### ISSUE THREAD

**Issue by vimalraj-a** [PolymerElements/paper-menu-button#43]
Dropdown size shrinking each time opening the dropdown. When I put ```no-animation``` attribute at <paper-menu-button> size  of the dropdown not shrinking.

hope shrink animation reducing the size of the element. 

```<paper-material class="dropdown-content style-scope paper-menu-button x-scope paper-material-0" elevation="1" style="box-sizing: border-box; max-height: 407px; max-width: 1175px;">```

```max-width``` and ```max-height``` varies whenever opens the dropdown.

**Comment by cdata** [comment]
Please provide a JSBin containing a set of reproducible steps.  For more details on filing issues, please refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md).
