### ISSUE TITLE
1.0.4 breaks paper-dropdown-menu / paper-menu

### ISSUE THREAD

**Issue by mkazlauskas** [PolymerElements/paper-menu-button#48]
After update to 1.0.4 my dropdown got completely broken. It opens in `open` state and clicking the button has no effect. No errors in console either.

Here's how it looks:

1.0.3

![1.0.3](http://i.imgur.com/h6X5u1E.png)

1.0.4.

![1.0.4](http://i.imgur.com/8eG7WpO.png)

HTML is pretty much as this:

```html
<paper-dropdown-menu>
      <paper-menu class="dropdown-content">
          <paper-item></paper-item>
      </paper-menu>
<paper-dropdown-menu>
```

**Comment by cdata** [comment]
Hi, thanks for reporting your bug. This report does not contain a reduced test case, so I'm going to close it for now. Please re-open it with a reduced test case when you have one!

Please also refer to our contributor guidelines for filing issues in the future: https://github.com/PolymerElements/paper-menu-button/blob/master/CONTRIBUTING.md
