### ISSUE TITLE
Scrollbar and interaction issue

### ISSUE THREAD

**Issue by gulyasfeccferenc** [PolymerElements/paper-menu-button#5]
With the added no-animation tag its works normally, when click outside the menu, its closing, but until i didn't close it, cannot scroll on the page and even the scrollbar is hiding. Is it the proper behaviour of the element or is there any way to prevent this?

Thanks in advance!

**Comment by cdata** [comment]
Hi, this an implementation detail of overlays in general. This mimics the behavior of the web browser when an overlay-like thing (think `<select>` element) is open. https://github.com/PolymerElements/iron-dropdown/pull/25 should have fixed this issue via a new `allow-outside-scroll` attribute. Please re-open if that is not a sufficient solution to your problem.
