### ISSUE TITLE
There's no way to keep the dialog open while clicking within dialog

### ISSUE THREAD

**Issue by mbergeron** [PolymerElements/paper-menu-button#51]
The problems is that there's no way to keep the dialog open after a click event happen within the dialog.

The feature was working properly a couple of weeks ago.

In the example below I'm supposed to be able to select multiple checkbox before closing down the dialog with a manual close or a click outside the dialog.

http://jsbin.com/tepura/edit?html,output

**Comment by miztroh** [comment]
+1 / bump @cdata 

Another example: http://jsbin.com/nupisequga/edit?html,output

**Comment by cdata** [comment]
Hi, thanks for reporting guys. Both of your test cases seem to work for me. Please re-open if you think this is still a problem!

**Comment by mbergeron** [comment]
It works fine now thank cdata
