### ISSUE TITLE
Demo: menu reopens itself after closed

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-menu-button#6]
1. Open a menu on https://elements.polymer-project.org/bower_components/paper-menu-button/demo/index.html
2. Click off it

The dropdown reappears after it closes itself

**Comment by ebidel** [comment]
I see this is fixed in https://github.com/PolymerElements/iron-dropdown/pull/10. Should we do a release?

**Comment by cdata** [comment]
If this is not fixed, please re-open!
