### ISSUE TITLE
Paper-menu-button doesn't always clean overflow hidden

### ISSUE THREAD

**Issue by eximius313** [PolymerElements/paper-menu-button#60]
Paper-menu-button doesn't always clean overflow hidden (especially after several quick clicks) and causes mouse scroll to stop working
![polymer_bug 1](https://cloud.githubusercontent.com/assets/5578017/12708627/b617bcec-c8a1-11e5-83c7-b2afad784a27.gif)

**Comment by cdata** [comment]
Thanks for filing an issue. We need to see a reduced test case in order to verify that there is a problem. Please re-open the issue when you have a test case, and consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!

**Comment by abdmob** [comment]
I've had the same issue and, actually, it's reproducing easily and had to fork a paper-menu-button to fix this and other issue.

**Comment by eximius313** [comment]
@cdata - just do several quick clicks on and outside the button

**Comment by notwaldorf** [comment]
@eximius313 I've tried this on the demo page several times, and can't repro. If you can produce a JSBin where you can repro this reliably, we'd love to take a look.
