### ISSUE TITLE
kill paper-material with fire

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-menu-button#74]
in accordance with the [Polymer Element Tracker](https://docs.google.com/spreadsheets/d/1m0SleaDfRTPzDvlnInip9x4FXT6O98M2W8jwZyHmNp8/edit#gid=1938185096), `paper-material` is deprecated and for performance should be "kill[ed] with fire".

**Comment by abdonrd** [comment]
@mgiuffrida "You need permission" for the Polymer Element Tracker. I request access.

**Comment by mgiuffrida** [comment]
@tjsavage is there a public version of the tracker?

**Comment by tjsavage** [comment]
This particular tracker we can't make public (just a tracker for balancing workload within the core team) but we're looking for a good way to make any info that might be broadly valuable public. "Kill with fire" sounds like a colorful note :smile:

**Comment by mgiuffrida** [comment]
Heh okay. Would you like to open a more nuanced bug that explains the issues with paper-material?

**Comment by abdonrd** [comment]
@tjsavage haha okey! :grin:

@mgiuffrida yes please. :)

**Comment by notwaldorf** [comment]
The TL; DR is that it's a bit of a performance anti-pattern to create a whole custom element just to get a box shadow. We have replaced it in other elements (like `paper-button`: https://github.com/PolymerElements/paper-button/blob/master/paper-button.html#L86) with just the style; I think something similar could be done here (a plain div with the right elevation applied to it).
